-- =============================================================================
-- Team Random FYDP — Production Supabase Schema
-- =============================================================================
-- This schema establishes the relational database structure, indexing,
-- automated update triggers, and Row Level Security (RLS) policies for
-- the Team Random FYDP platform.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Helper Function: Automatic `updated_at` Timestamp Trigger
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- -----------------------------------------------------------------------------
-- 2. Members Table
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS members (
    slug TEXT PRIMARY KEY,
    student_id TEXT,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT DEFAULT 'Not provided',
    gender TEXT,
    department TEXT DEFAULT 'Department of Computer Science & Engineering',
    institution TEXT DEFAULT 'United International University',
    role TEXT NOT NULL,
    short_role TEXT,
    tagline TEXT,
    initials TEXT,
    image TEXT,
    admin_avatar_style TEXT,
    image_position TEXT,
    image_fit TEXT,
    placeholder TEXT,
    github TEXT,
    linkedin TEXT,
    about TEXT,
    responsibilities JSONB DEFAULT '[]'::jsonb,
    skills JSONB DEFAULT '[]'::jsonb,
    focus JSONB DEFAULT '[]'::jsonb,
    custom_links JSONB DEFAULT '[]'::jsonb,
    privacy JSONB DEFAULT '{"email": true, "phone": true, "github": true, "linkedin": true}'::jsonb,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_members_student_id ON members(student_id);
CREATE INDEX IF NOT EXISTS idx_members_email ON members(email);
CREATE INDEX IF NOT EXISTS idx_members_display_order ON members(display_order);

DROP TRIGGER IF EXISTS set_members_updated_at ON members;
CREATE TRIGGER set_members_updated_at
    BEFORE UPDATE ON members
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------------------------------
-- 3. Tasks Table (Directives / Kanban)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT DEFAULT '',
    assignee TEXT NOT NULL,
    assignee_slug TEXT REFERENCES members(slug) ON UPDATE CASCADE ON DELETE SET NULL,
    priority TEXT NOT NULL DEFAULT 'MEDIUM' CHECK (priority IN ('HIGH', 'MEDIUM', 'LOW')),
    due_date TEXT,
    status TEXT NOT NULL DEFAULT 'TODO' CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE')),
    created_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_tasks_assignee_slug ON tasks(assignee_slug);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks(priority);
CREATE INDEX IF NOT EXISTS idx_tasks_created_at ON tasks(created_at DESC);

DROP TRIGGER IF EXISTS set_tasks_updated_at ON tasks;
CREATE TRIGGER set_tasks_updated_at
    BEFORE UPDATE ON tasks
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------------------------------
-- 4. Sprint Logs Table (Homepage Timeline & Sprint Updates)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sprint_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week TEXT NOT NULL,
    title TEXT NOT NULL,
    date TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'upcoming')),
    category TEXT NOT NULL DEFAULT 'Engineering',
    author TEXT NOT NULL,
    highlights JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_sprint_logs_status ON sprint_logs(status);
CREATE INDEX IF NOT EXISTS idx_sprint_logs_created_at ON sprint_logs(created_at DESC);

DROP TRIGGER IF EXISTS set_sprint_logs_updated_at ON sprint_logs;
CREATE TRIGGER set_sprint_logs_updated_at
    BEFORE UPDATE ON sprint_logs
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------------------------------
-- 5. Team Notes Table (Internal Directives & Portal Updates)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS team_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author TEXT NOT NULL,
    author_role TEXT,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    tag TEXT NOT NULL DEFAULT 'General',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_team_notes_tag ON team_notes(tag);
CREATE INDEX IF NOT EXISTS idx_team_notes_created_at ON team_notes(created_at DESC);

DROP TRIGGER IF EXISTS set_team_notes_updated_at ON team_notes;
CREATE TRIGGER set_team_notes_updated_at
    BEFORE UPDATE ON team_notes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------------------------------
-- 6. Audit Logs Table (Security & Activity History)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    formatted_time TEXT,
    actor_name TEXT NOT NULL,
    actor_role TEXT NOT NULL,
    action TEXT NOT NULL,
    details TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'GENERAL',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON audit_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_type ON audit_logs(type);

-- -----------------------------------------------------------------------------
-- 7. Banner Config Table (Singleton record for homepage media)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS banner_config (
    id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    mode TEXT NOT NULL DEFAULT 'auto' CHECK (mode IN ('auto', 'video', 'image')),
    video_url TEXT NOT NULL DEFAULT '/team-banner.mp4',
    image_url TEXT NOT NULL DEFAULT '/team-banner.jpg',
    headline TEXT NOT NULL DEFAULT 'Team Random',
    tagline TEXT NOT NULL DEFAULT 'Engineering scalable software architecture & intelligent computing solutions.',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

DROP TRIGGER IF EXISTS set_banner_config_updated_at ON banner_config;
CREATE TRIGGER set_banner_config_updated_at
    BEFORE UPDATE ON banner_config
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------------------------------
-- 8. Project Info Table (Singleton record for project metadata)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS project_info (
    id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    title TEXT NOT NULL,
    short_title TEXT NOT NULL,
    domain TEXT NOT NULL,
    status TEXT NOT NULL,
    progress_percent INTEGER NOT NULL DEFAULT 0,
    supervisor JSONB NOT NULL DEFAULT '{}'::jsonb,
    abstract TEXT NOT NULL,
    tech_stack JSONB NOT NULL DEFAULT '[]'::jsonb,
    milestones JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

DROP TRIGGER IF EXISTS set_project_info_updated_at ON project_info;
CREATE TRIGGER set_project_info_updated_at
    BEFORE UPDATE ON project_info
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------------------------------
-- 9. User Credentials Table (Secure Auth & Password Hashes)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_credentials (
    slug TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    aliases JSONB DEFAULT '[]'::jsonb,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'MEMBER',
    role_title TEXT,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_user_credentials_username ON user_credentials(username);
CREATE INDEX IF NOT EXISTS idx_user_credentials_email ON user_credentials(email);

DROP TRIGGER IF EXISTS set_user_credentials_updated_at ON user_credentials;
CREATE TRIGGER set_user_credentials_updated_at
    BEFORE UPDATE ON user_credentials
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();


-- =============================================================================
-- Row Level Security (RLS) Configuration
-- =============================================================================
-- Server-side mutations will be performed via the Supabase Secret Key (Server Client)
-- (which automatically bypasses RLS). Public read policies are strictly read-only.
-- =============================================================================

-- Enable RLS on all tables
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE sprint_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE banner_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_credentials ENABLE ROW LEVEL SECURITY;

-- 1. Public Read Policies
DROP POLICY IF EXISTS "Public can view members" ON members;
CREATE POLICY "Public can view members"
    ON members FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Public can view sprint logs" ON sprint_logs;
CREATE POLICY "Public can view sprint logs"
    ON sprint_logs FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Public can view banner config" ON banner_config;
CREATE POLICY "Public can view banner config"
    ON banner_config FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Public can view project info" ON project_info;
CREATE POLICY "Public can view project info"
    ON project_info FOR SELECT
    USING (true);

-- 2. Protected Internal Tables (Tasks, Notes, Audit Logs, User Credentials)
-- No public anonymous access is granted to user_credentials or sensitive tables.
-- Trusted Next.js server endpoints use SUPABASE_SECRET_KEY.
